apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskconsumer
spec:
  selector:
    matchLabels:
      app: taskconsumer
  template:
    metadata:
      labels:
        app: taskconsumer
    spec:
      containers:
      - name: taskconsumerpod
        image: alvinsoo1993/tasksconsumer
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            cpu: "200m"
            memory: "64Mi"        
        ports:
          - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: taskconsumer
spec:
  selector:
    app: taskconsumer
  ports:
  - port: 80
    targetPort: 80
